#!/usr/bin/env bash
d() {
  [ -n "$DEBUG" ]
}
debug() {
  d && echo "${@}" > /dev/stderr
}

unset tmpdir
unset tmpfile
unset template_name
atexit() {
  debug delete temporary
  [[ -n "${tmpdir-}" ]] && rm -rf "${tmpdir}"
}
trap atexit EXIT
trap 'trap - EXIT; atexit; exit -1' INT PIPE TERM

tmpdir="$(mktemp -d /tmp/j1XXXXXX)"
tmpfile=$tmpdir/Main.java
template_name=~/.j1template

if [ -f "$template_name" ]; then
  tpl=$(cat $template_name)
  debug read template
else
  tpl=$(cat << DEFAULT_SOURCE_CODE
public class Main {
  public static void main(String[] args){
  \${@};
  }
}
DEFAULT_SOURCE_CODE
)
  debug use default template
fi

debug template is...
debug "${tpl}"

tpld=$(cat <<OUTER
cat <<EOF
${tpl}
EOF
OUTER
)
eval "${tpld}" > $tmpfile

debug source code is...
d && cat $tmpfile > /dev/stderr

debug '=========='
{
  cd $tmpdir
  javac $tmpfile
  java -cp . Main
}
debug '=========='



