#!/usr/bin/env bash

temp=$(mktemp /tmp/JXXXXXX)
class=$(basename $temp)
outdir=$(dirname $temp)

template_name=~/.j1template

{
  if [ -f $template_name ]; then
    cat $template_name
  else
    cat << DEFAULT_SOURCE_CODE
public class __CLASSNAME__ {
  public static void main(String[] args){
    __CONTENTS__
  }
}
DEFAULT_SOURCE_CODE

  fi
} | sed -e "s/__CLASSNAME__/$class/" -e "s/__CONTENTS__/$@/" >> $temp.java

#cat $temp.java

{
  javac $temp.java
  java -cp $outdir $class < /dev/stdin
}
